apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-cluster-issuer
spec:
  acme:
    email: {{ .Values.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.certSecretKey }}-secret
    solvers:
      - selector:
          dnsZones:
            - {{ .Values.hostedZone }}
        dns01:
          route53:
            region: {{ .Values.region }}
            hostedZoneID: {{ .Values.hostedZoneId }}
